apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: frontend-image
    newName: ttcsacr20260519.azurecr.io/ttcs/frontend
    newTag: e4a898bf7e23
  - name: auth-gateway-image
    newName: ttcsacr20260519.azurecr.io/ttcs/auth-gateway
    newTag: latest
  - name: be-service-image
    newName: ttcsacr20260519.azurecr.io/ttcs/be-service
    newTag: latest
  - name: qr-service-image
    newName: ttcsacr20260519.azurecr.io/ttcs/qr-service
    newTag: latest
