apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: frontend-image
    newName: ttcsacr20260519.azurecr.io/ttcs/frontend
    newTag: c35081101a65
  - name: auth-gateway-image
    newName: ttcsacr20260519.azurecr.io/ttcs/auth-gateway
    newTag: 133c26634a09
  - name: be-service-image
    newName: ttcsacr20260519.azurecr.io/ttcs/be-service
    newTag: 664de21c62c5
  - name: qr-service-image
    newName: ttcsacr20260519.azurecr.io/ttcs/qr-service
    newTag: 878e967f6feb
