apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ttcs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/REPLACE_ME_DEPLOY_REPO.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ttcs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
