apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - shared-config.yaml
  - platform/mongodb.yaml
  - platform/redis.yaml
  - platform/rabbitmq.yaml
  - apps/frontend.yaml
  - apps/gateway.yaml
  - apps/auth-gateway.yaml
  - apps/be-service-api.yaml
  - apps/be-checkin-sync-worker.yaml
  - apps/be-service-scheduler.yaml
  - apps/qr-service-api.yaml
  - apps/qr-sync-worker.yaml
  - apps/qr-attendance-worker.yaml
