apiVersion: v1
kind: Secret
metadata:
  name: ttcs-app-secrets
  namespace: ttcs
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_ME_JWT_SECRET"
  MONGO_INITDB_ROOT_USERNAME: "ttcs_root"
  MONGO_INITDB_ROOT_PASSWORD: "REPLACE_ME_MONGO_PASSWORD"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
  CLOUDINARY_NAME: "REPLACE_ME_CLOUDINARY_NAME"
  CLOUDINARY_API_KEY: "REPLACE_ME_CLOUDINARY_API_KEY"
  CLOUDINARY_API_SECRET: "REPLACE_ME_CLOUDINARY_API_SECRET"
  CLOUDINARY_FOLDER: "REPLACE_ME_CLOUDINARY_FOLDER"
